const macros =  {
    "\\CC": "\\mathbb{C}",
    "\\HH": "\\mathbb{H}",
    "\\NN": "\\mathbb{N}",
    "\\OO": "\\mathscr{O}",
    "\\PP": "\\mathbb{P}",
    "\\QQ": "\\mathbb{Q}",
    "\\RR": "\\mathbb{R}",
    "\\ZZ": "\\mathbb{Z}",
    "\\iprod": "\\lrcorner",
    "\\ihom": "\\underline{\\Hom}",
    "\\shar": "\\#",
    "\\shom": "\\mathcal{H}om",
    "\\sext": "\\mathcal{E}xt",
    "\\dirac": "\\cancel{D}",
    "\\abs": "\\left|#1\\right|",
    "\\rinterval": "[#1, #2[",
    "\\linterval": "]#1,#2]",
    "\\xrightarrow": "\\overset{#1}{\to}",
    "\\norm": "\\left\\lVert#1\\right\\rVert",

    "\\End": "\\operatorname{End}",
    "\\Hom": "\\operatorname{Hom}",
    "\\aut": "\\operatorname{Aut}",
    "\\ch": "\\operatorname{ch}",
    "\\colim": "\\operatorname{colim}",
    "\\coker": "\\operatorname{coker}",
    "\\deg": "\\operatorname{deg}",
    "\\dim": "\\operatorname{dim}",
    "\\ex": "\\operatorname{Ex}",
    "\\Ext": "\\operatorname{Ext}",
    "\\Tor": "\\operatorname{Tor}",
    "\\hol": "\\operatorname{Hol}",
    "\\id": "\\operatorname{id}",
    "\\im": "\\operatorname{im}",
    "\\ito": "\\stackrel{\\sim}{\\rightarrow}",
    "\\ker": "\\operatorname{ker}",
    "\\sgn": "\\operatorname{sgn}",
    "\\tr": "\\operatorname{tr}",

    "\\pd": "\\operatorname{P.D.}",
    "\\pl": "\\operatorname{PL}",
    "\\topo": "\\operatorname{Top}",

    "\\GL": "\\operatorname{GL}",
    "\\PGL": "\\operatorname{PGL}",
    "\\SL": "\\operatorname{SL}",
    "\\SO": "\\operatorname{SO}",
    "\\SU": "\\operatorname{SU}",
    "\\Sp": "\\operatorname{Sp}",
    "\\Spin": "\\operatorname{Spin}",
    "\\U": "\\operatorname{U}",

    "\\Char": "\\operatorname{Char}",
    "\\ks": "\\operatorname{KS}",
    "\\sq": "\\operatorname{Sq}",

    "\\art": "\\operatorname{Art}",
    "\\Aut": "\\operatorname{Aut}",
    "\\cone": "\\operatorname{Cone}",
    "\\conv": "\\operatorname{Conv}",
    "\\depth": "\\operatorname{depth}",
    "\\dimh": "\\operatorname{dh}",
    "\\dif": "\\operatorname{d}",
    "\\hilb": "\\operatorname{Hilb}",
    "\\pic": "\\operatorname{Pic}",
    "\\rk": "\\operatorname{rk}",
    "\\spec": "\\operatorname{Spec}",
    "\\supp": "\\operatorname{Supp}",
    "\\virdim": "\\operatorname{virdim}",

    "\\Gal": "\\operatorname{Gal}",
    "\\Frob": "\\operatorname{Frob}",
    "\\Ind": "\\operatorname{Ind}",
    "\\nm": "\\operatorname{Nm}"
};
